### ISSUE TITLE
Serious tidy up!!

### ISSUE THREAD

**Issue by hollandben** [hollandben/grunt-cache-bust#107]
This repo is getting properly messy. List of things to get done:

- [x] Make sure all files adhere to the settings in `.editorconfig` - #109 
- [ ] Better documentation - there are a lot of settings and a shorter snapshot of them would be better
- [x] Correspond each `cacheBust` test in the `Gruntfile.js` file with each test folder - #110 
- [x] Create a folder for each set of tests with it's assets inside. Will keep them better contained - #110 
- [x] Reduce the size of the assets used so they take up less space, i.e. smaller images - #116

**Comment by MrHyde** [comment]
+1 on this :)
